spring.application.name=employee-management-api
server.port=8081
# PostgreSQL Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db

spring.datasource.username=postgres

spring.datasource.password=YOUR_PASSWORD